// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AccordionController from "./accordion_controller"
application.register("accordion", AccordionController)

import EditorController from "./editor_controller"
application.register("editor", EditorController)

import InputController from "./input_controller"
application.register("input", InputController)

import KebabController from "./kebab_controller"
application.register("kebab", KebabController)

import ReportStatusController from "./report_status_controller"
application.register("report-status", ReportStatusController)

import TagController from "./tag_controller"
application.register("tag", TagController)
